name: /data/home/emmanuelayanful/envs/reprocode
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiodns=3.5.0=py311h06a4308_1
  - aiohappyeyeballs=2.6.1=py311h06a4308_0
  - aiohttp=3.13.2=py311hee96239_0
  - aiosignal=1.4.0=py311h06a4308_0
  - arrow-cpp=21.0.0=hac1acdb_1
  - attrs=25.4.0=py311h06a4308_2
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - blas=1.0=openblas
  - boto3=1.40.54=py311h06a4308_0
  - botocore=1.40.54=py311h06a4308_0
  - bottleneck=1.4.2=py311haa0f9ac_1
  - brotlicffi=1.1.0.0=py311hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2025.11.12=py311h06a4308_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - click=8.2.1=py311h06a4308_1
  - datasets=3.3.2=py311h06a4308_0
  - dill=0.3.8=py311h06a4308_0
  - expat=2.7.3=h3385a95_0
  - filelock=3.20.0=py311h06a4308_0
  - frozenlist=1.8.0=py311hbdd6827_0
  - fsspec=2024.12.0=py311h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - hf-xet=1.1.8=py311h84c0859_0
  - huggingface_hub=0.34.4=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=py311h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jansson=2.14=h5eee18b_1
  - jmespath=1.0.1=py311h06a4308_0
  - joblib=1.5.2=py311h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=8.16.0=heebcbe5_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.71.0=h2d74bed_0
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsentencepiece=0.2.0=h9a1b9f3_5
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.22.0=hd8eb582_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - multidict=6.7.0=py311hee96239_0
  - multiprocess=0.70.15=py311h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nomkl=3.0=0
  - numexpr=2.14.1=py311ha5a4a6c_0
  - numpy=2.3.5=py311h35d6838_0
  - numpy-base=2.3.5=py311h4bc27c9_0
  - openssl=3.0.18=hd6dcaed_0
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=py311h06a4308_1
  - pandas=2.3.3=py311h23c847b_1
  - pip=25.3=pyhc872135_0
  - propcache=0.3.1=py311h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=21.0.0=py311h505adc9_0
  - pycares=4.10.0=py311ha137689_0
  - pycparser=2.23=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_1
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-dotenv=1.1.0=py311h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h5eee18b_0
  - pytz=2025.2=py311h06a4308_0
  - pyyaml=6.0.3=py311h591646f_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - regex=2025.9.1=py311hee96239_0
  - requests=2.32.5=py311h06a4308_1
  - s2n=1.5.14=hdbd6064_0
  - s3transfer=0.14.0=py311h06a4308_0
  - sacremoses=0.1.1=py311h06a4308_0
  - scikit-learn=1.7.2=py311h505adc9_0
  - scipy=1.16.3=py311he2bc341_0
  - sentencepiece-spm=0.2.0=h9a1b9f3_5
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=py311h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.51.0=h2a70700_0
  - threadpoolctl=3.5.0=py311h7040dfc_1
  - tk=8.6.15=h54e0aa7_0
  - tokenizers=0.22.1=py311h4b931ed_0
  - tqdm=4.67.1=py311h7040dfc_1
  - typing-extensions=4.15.0=py311h06a4308_0
  - typing_extensions=4.15.0=py311h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvloop=0.22.1=py311h939ff40_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py311hee96239_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - accelerate==1.12.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - pillow==11.3.0
      - psutil==7.1.3
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - sympy==1.13.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - transformers==4.57.3
      - triton==3.1.0
prefix: /data/home/emmanuelayanful/envs/reprocode
